"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$directory$all$character"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
staged = '[+$count](green)'
modified = "ğŸ“${count}"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[python]
format = '[${pyenv_prefix}(\($virtualenv\) )]($style)'

[golang]
symbol = "î˜§ "
